/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./components/BottomNav.vue')['default']
    ExerciseCard: typeof import('./components/ExerciseCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HistoryScreen: typeof import('./screens/HistoryScreen.vue')['default']
    HomeScreen: typeof import('./screens/HomeScreen.vue')['default']
    IconHeroiconsTrash: typeof import('~icons/heroicons/trash')['default']
    SetRow: typeof import('./components/SetRow.vue')['default']
    StartWorkoutSessionCard: typeof import('./components/StartWorkoutSessionCard.vue')['default']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
    WorkoutDetail: typeof import('./components/WorkoutDetail.vue')['default']
    WorkoutListItem: typeof import('./components/WorkoutListItem.vue')['default']
    WorkoutSessionScreen: typeof import('./screens/WorkoutSessionScreen.vue')['default']
  }
}
